# Generated by Django 4.0 on 2022-10-10 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_fee_type_payment_name_alter_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='state_ID',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
